/**
 * Shared test helpers for GraphQL resolver integration tests.
 *
 * Provides server initialization, catalog setup verification, and a
 * thin wrapper around Apollo Server's executeOperation to normalize
 * the response into the familiar { data, errors } shape.
 */

import { ApolloServer } from '@apollo/server';
import { schema } from '../../../../src/schema/index.js';
import { createLoaders } from '../../../../src/loaders/index.js';
import { databaseManager } from '../../../../src/db/index.js';
import { redis } from '../../../../src/cache/index.js';
import { v4 as uuidv4 } from 'uuid';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ─── Résolution du répertoire courant ─────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Interfaces ───────────────────────────────────────────────────────────────

/** Résultat d'une opération GraphQL normalisé. */
export interface GraphQLResult {
  data: Record<string, unknown> | null;
  errors?: ReadonlyArray<{ message: string; extensions?: Record<string, unknown> }>;
}

/** Paramètre d'opération transmis à executeOperation d'Apollo Server. */
export interface GraphQLOperation {
  query: string;
  variables?: Record<string, unknown>;
}

// ─── État du serveur partagé ──────────────────────────────────────────────────

// Instance unique du serveur Apollo — réutilisée entre tous les tests
let _server: ApolloServer | null = null;

/**
 * Ensures the test catalog has been initialized by npm run test:setup.
 *
 * Tests run in READ_ONLY mode to allow multiple Jest VM contexts to open
 * the same DuckLake file simultaneously; the catalog must pre-exist.
 *
 * Also reconciles the schema list and probes the schema version of every
 * schema, exactly as src/server.ts does before starting: without it the
 * version guard would have no verdict to enforce.
 *
 * Raises:
 *     Error: If the test catalog file is not found at the expected path.
 */
export const ensureSetup = async (): Promise<void> => {
  // Vérification de l'existence du catalogue de test
  const catalogPath = path.resolve(__dirname, '../../../../data/test-default.ducklake');
  if (!fs.existsSync(catalogPath)) {
    throw new Error(
      `Test catalog not found: ${catalogPath}\n` +
        `Run "npm run test:setup" before running the resolver tests.`,
    );
  }

  // Réconciliation des schémas + sondage des versions, comme au démarrage
  await databaseManager.initSchemas();
};

/**
 * Empties the Redis entries of the aggregates (`aggregated-facts:*`).
 *
 * Redis outlives the test data regenerated by every `npm run test:setup`
 * (random values, same data version): an entry written by a previous run
 * would answer without reaching the loader, with the values of the former
 * data. Accounts for the client's `keyPrefix`; with Redis down the loader
 * runs on every call and there is nothing to clear.
 */
// Vidage du cache des agrégats, sensible au préfixe de clés d'ioredis
export const clearAggregatedCache = async (): Promise<void> => {
  try {
    const prefix =
      (redis as unknown as { options: { keyPrefix?: string } }).options.keyPrefix ?? '';
    let cursor = '0';
    do {
      const [next, keys] = await redis.scan(
        cursor,
        'MATCH',
        `${prefix}aggregated-facts:*`,
        'COUNT',
        100,
      );
      if (keys.length > 0) await redis.del(...keys.map((key) => key.slice(prefix.length)));
      cursor = next;
    } while (cursor !== '0');
  } catch {
    // Redis indisponible : aucun cache à vider
  }
};

/**
 * Returns the shared Apollo Server instance, creating it on first call.
 *
 * Singleton pattern — a single server is started once per test suite to
 * avoid repeated startup overhead across test files.
 *
 * @returns Started ApolloServer instance.
 */
export const getServer = async (): Promise<ApolloServer> => {
  // Initialisation du serveur au premier appel
  if (!_server) {
    _server = new ApolloServer({ schema });
    await _server.start();
  }
  return _server;
};

/**
 * Executes a GraphQL operation and normalizes the Apollo Server v5 response.
 *
 * Mirrors the contextValue built by createContext in src/server.ts: catalog
 * and schema are resolved from GraphQL arguments only (no HTTP header).
 *
 * @param server - Running ApolloServer instance.
 * @param operation - GraphQL query string and optional variables.
 *
 * @returns Normalized { data, errors } result object.
 */
export const execute = async (
  server: ApolloServer,
  operation: GraphQLOperation,
): Promise<GraphQLResult> => {
  // Construction du contexte de requête — identique à src/server.ts
  const defaultCatalog = databaseManager.getDefaultCatalog();
  const { body } = await server.executeOperation(operation, {
    contextValue: {
      requestId: uuidv4(),
      loaders: createLoaders(null, null),
      databaseManager,
      // Résolution des loaders pour un catalogue/schéma cible
      getLoadersForCatalog: (catalog: string | null, schema: string | null = null) => {
        const targetCatalog = databaseManager.validateCatalogRouting(catalog);
        if (targetCatalog === defaultCatalog && !schema) return null;
        return createLoaders(targetCatalog, schema);
      },
    },
  });

  // Normalisation du format de réponse Apollo Server v5
  if (body.kind === 'single') return body.singleResult as GraphQLResult;
  return { data: null, errors: [{ message: 'Unexpected incremental response' }] };
};
