version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: npm
    directory: '/docs-site'
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docs

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
