// Site « boîte à outils » — publié sous /toolbox/ (réutilisable d'un projet à l'autre) :
// installation, configuration, déploiement, architecture, politique de versioning et
// référence du code TypeScript (TypeDoc). Build : `npm run docs:build:toolbox`
// (racine du dépôt).
//
// TypeDoc est lancé avant le build (npm run docs:typedoc) et écrit ses pages markdown
// dans toolbox/code-reference/.

import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {
  API_BASE_URL,
  EDIT_URL,
  REPO_URL,
  TOOLBOX_BASE_URL,
  buildFooter,
  crossSiteHref,
  sharedPrism,
  sharedSiteFields,
} from './site-shared';

const config: Config = {
  ...sharedSiteFields,
  title: 'GraphQL DuckLake API — Toolbox',
  tagline:
    'Reusable building blocks: setup, configuration, deployment, architecture and code reference',
  baseUrl: TOOLBOX_BASE_URL,

  // Aucun fichier statique : le SDL et l'introspection appartiennent au site API
  staticDirectories: [],

  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'codeReference',
        path: 'toolbox/code-reference',
        routeBasePath: 'code-reference',
        sidebarPath: './toolbox/sidebars-code-reference.ts',
        // Two passes on the autogenerated sidebar:
        //
        //   1. dedupe: remove TypeDoc module-summary doc items when a same-named
        //      category exists at the same level (prevents duplicates like
        //      "cache" doc + "cache" folder). Applied recursively.
        //
        //   2. unlinkAutoCategoryDocs: when a category was auto-linked to a
        //      doc inside it (e.g. utils/utils.md auto-promoted as the utils/
        //      index page), drop the link and surface the doc as a regular
        //      item, so the folder behaves like a pure container — consistent
        //      with cache/, db/, etc.
        sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
          const items = await defaultSidebarItemsGenerator({
            defaultSidebarItemsGenerator,
            ...args,
          });

          const dedupe = (level) => {
            const categoryLabels = new Set(
              level
                .filter((item) => item.type === 'category' && item.label)
                .map((item) => item.label.toLowerCase()),
            );
            return level
              .filter((item) => {
                if (item.type !== 'doc') return true;
                // TypeDoc files have no frontmatter, so item.label may be undefined.
                // Fall back to item.id (last path segment) for matching.
                const id = (item.id ?? '').split('/').pop()?.toLowerCase() ?? '';
                const label = (item.label ?? '').toLowerCase();
                return !categoryLabels.has(id) && !categoryLabels.has(label);
              })
              .map((item) =>
                item.type === 'category' && Array.isArray(item.items)
                  ? { ...item, items: dedupe(item.items) }
                  : item,
              );
          };

          const unlinkAutoCategoryDocs = (level) =>
            level.map((item) => {
              if (item.type !== 'category') return item;
              let nextItems = Array.isArray(item.items) ? item.items : [];
              const next = { ...item };
              if (item.link?.type === 'doc') {
                const linkedId = item.link.id;
                const alreadyPresent = nextItems.some(
                  (child) => child.type === 'doc' && child.id === linkedId,
                );
                if (!alreadyPresent) {
                  nextItems = [...nextItems, { type: 'doc', id: linkedId }];
                }
                delete next.link;
              }
              next.items = unlinkAutoCategoryDocs(nextItems);
              return next;
            });

          return unlinkAutoCategoryDocs(dedupe(items));
        },
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'toolbox/docs',
          sidebarPath: './toolbox/sidebars.ts',
          editUrl: EDIT_URL,
          routeBasePath: '/',
        },
        pages: false,
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/social-card.png',
    navbar: {
      title: 'GraphQL DuckLake API — Toolbox',
      items: [
        { type: 'docSidebar', sidebarId: 'docs', position: 'left', label: 'Docs' },
        {
          type: 'docSidebar',
          docsPluginId: 'codeReference',
          sidebarId: 'codeReference',
          position: 'left',
          label: 'Code Reference',
        },
        // Autre site : page complète (pas de navigation SPA entre deux builds)
        {
          href: crossSiteHref(API_BASE_URL),
          label: 'API & Data',
          position: 'left',
          target: '_self',
        },
        { href: REPO_URL, label: 'GitHub', position: 'right' },
      ],
    },
    footer: buildFooter([
      { label: 'Getting Started', to: '/getting-started/installation' },
      { label: 'Configuration', to: '/configuration/overview' },
      { label: 'Deployment', to: '/deployment/overview' },
      {
        label: 'API & Data (GraphQL reference, export, data dictionary)',
        href: crossSiteHref(API_BASE_URL),
      },
    ]),
    prism: sharedPrism,
    algolia: undefined,
  } satisfies Preset.ThemeConfig,
};

export default config;
