import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/testing',
      ],
    },
    {
      type: 'category',
      label: 'API Guide',
      collapsed: false,
      items: [
        'api-guide/overview',
        'api-guide/queries',
        'api-guide/examples',
      ],
    },
    {
      type: 'category',
      label: 'Configuration Reference',
      items: [
        'configuration/overview',
        'configuration/api',
        'configuration/database',
        'configuration/security',
        'configuration/cache',
        'configuration/logging',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/security',
        'architecture/caching',
        'architecture/data-loading',
      ],
    },
    {
      type: 'category',
      label: 'Code Reference',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'code-reference' }],
    },
  ],
};

export default sidebars;
