/**
 * Fails when a tracked generated file is not up to date with its source: the
 * regenerated file must equal the committed one.
 *
 * Usage: node scripts/schema-check.mjs [file] [command…]
 *   - schema:check   → `schema.graphql` (default), regenerated by `npm run schema:generate`;
 *   - codegen:check  → `src/generated/graphql.ts`, regenerated by `npm run codegen`.
 * The command words only feed the hint printed on failure.
 */

import { spawnSync } from 'node:child_process';

const FILE = process.argv[2] ?? 'schema.graphql';
const COMMAND = process.argv.length > 3 ? process.argv.slice(3).join(' ') : 'npm run schema:generate';
const HINT = `${FILE} est périmé : lancer ${COMMAND} et commiter.`;

const git = (...args) => spawnSync('git', args, { encoding: 'utf8' });

// `git diff` ignores untracked files: a never-committed schema.graphql must not pass.
if (git('ls-files', '--error-unmatch', FILE).status !== 0) {
  console.error(`${FILE} n'est pas suivi par git. ${HINT}`);
  process.exit(1);
}

const diff = git('diff', '--exit-code', '--', FILE);
if (diff.status !== 0) {
  process.stdout.write(diff.stdout);
  console.error(HINT);
  process.exit(1);
}

console.log(`${FILE} est à jour.`);
