name: Release Helm Chart

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

concurrency:
  group: release-chart
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Add chart dependencies repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm
          pages_branch: gh-pages-charts
          mark_as_latest: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
